// Generated by gothicgo/bootstrap - Do not modify

package gothicgo

import (
	"github.com/testify/assert"
	"testing"
)

func TestArrayTypeTypeGen(t *testing.T) {
	x := IntType.Array(5)

	assert.Equal(t, ArrayKind, x.Kind())
	assert.Equal(t, PkgBuiltin(), x.PackageRef())

	n := x.Named("Foo")
	assert.Equal(t, "Foo", n.Name())
	assert.Equal(t, x, n.T)

	n = x.Unnamed()
	assert.Equal(t, "", n.Name())
	assert.Equal(t, x, n.T)

	p := x.Pointer()
	assert.Equal(t, PointerKind, p.Kind())
	assert.Equal(t, x, p.Elem())

	s := x.Slice()
	assert.Equal(t, SliceKind, s.Kind())
	assert.Equal(t, x, s.Elem())

	a := x.Array(13)
	assert.Equal(t, ArrayKind, a.Kind())
	assert.Equal(t, x, a.Elem())

	mp := x.AsMapElem(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Elem())

	mp = x.AsMapKey(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Key)

	assert.Equal(t, IntType, x.Elem())

	str := PrefixWriteToString(x, DefaultPrefixer)
	assert.Equal(t, "[5]int", str)
}

func TestBuiltinTypeGen(t *testing.T) {
	x := IntType

	assert.Equal(t, IntKind, x.Kind())
	assert.Equal(t, PkgBuiltin(), x.PackageRef())

	n := x.Named("Foo")
	assert.Equal(t, "Foo", n.Name())
	assert.Equal(t, x, n.T)

	n = x.Unnamed()
	assert.Equal(t, "", n.Name())
	assert.Equal(t, x, n.T)

	p := x.Pointer()
	assert.Equal(t, PointerKind, p.Kind())
	assert.Equal(t, x, p.Elem())

	s := x.Slice()
	assert.Equal(t, SliceKind, s.Kind())
	assert.Equal(t, x, s.Elem())

	a := x.Array(13)
	assert.Equal(t, ArrayKind, a.Kind())
	assert.Equal(t, x, a.Elem())

	mp := x.AsMapElem(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Elem())

	mp = x.AsMapKey(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Key)

	str := PrefixWriteToString(x, DefaultPrefixer)
	assert.Equal(t, "int", str)
}

func TestTypeRefTypeGen(t *testing.T) {
	pkg := MustPackageRef("foo")
	x := pkg.NewTypeRef("Bar", IntType)

	assert.Equal(t, TypeDefKind, x.Kind())
	assert.Equal(t, pkg, x.PackageRef())

	n := x.Named("Foo")
	assert.Equal(t, "Foo", n.Name())
	assert.Equal(t, x, n.T)

	n = x.Unnamed()
	assert.Equal(t, "", n.Name())
	assert.Equal(t, x, n.T)

	p := x.Pointer()
	assert.Equal(t, PointerKind, p.Kind())
	assert.Equal(t, x, p.Elem())

	s := x.Slice()
	assert.Equal(t, SliceKind, s.Kind())
	assert.Equal(t, x, s.Elem())

	a := x.Array(13)
	assert.Equal(t, ArrayKind, a.Kind())
	assert.Equal(t, x, a.Elem())

	mp := x.AsMapElem(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Elem())

	mp = x.AsMapKey(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Key)

	assert.Equal(t, IntType, x.Elem())

	str := PrefixWriteToString(x, DefaultPrefixer)
	assert.Equal(t, "foo.Bar", str)
}

func TestFuncTypeTypeGen(t *testing.T) {
	args := []NameType{
		IntType.Named("a"),
		StringType.Named("b"),
	}
	x := NewFuncType("Foo", args...).
		UnnamedRets(StringType)

	assert.Equal(t, FuncKind, x.Kind())
	assert.Equal(t, PkgBuiltin(), x.PackageRef())

	n := x.Named("Foo")
	assert.Equal(t, "Foo", n.Name())
	assert.Equal(t, x, n.T)

	n = x.Unnamed()
	assert.Equal(t, "", n.Name())
	assert.Equal(t, x, n.T)

	p := x.Pointer()
	assert.Equal(t, PointerKind, p.Kind())
	assert.Equal(t, x, p.Elem())

	s := x.Slice()
	assert.Equal(t, SliceKind, s.Kind())
	assert.Equal(t, x, s.Elem())

	a := x.Array(13)
	assert.Equal(t, ArrayKind, a.Kind())
	assert.Equal(t, x, a.Elem())

	mp := x.AsMapElem(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Elem())

	mp = x.AsMapKey(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Key)

	str := PrefixWriteToString(x, DefaultPrefixer)
	assert.Equal(t, "func(int, string) string", str)
}

func TestMapTypeTypeGen(t *testing.T) {
	x := MapOf(IntType, StringType)

	assert.Equal(t, MapKind, x.Kind())
	assert.Equal(t, PkgBuiltin(), x.PackageRef())

	n := x.Named("Foo")
	assert.Equal(t, "Foo", n.Name())
	assert.Equal(t, x, n.T)

	n = x.Unnamed()
	assert.Equal(t, "", n.Name())
	assert.Equal(t, x, n.T)

	p := x.Pointer()
	assert.Equal(t, PointerKind, p.Kind())
	assert.Equal(t, x, p.Elem())

	s := x.Slice()
	assert.Equal(t, SliceKind, s.Kind())
	assert.Equal(t, x, s.Elem())

	a := x.Array(13)
	assert.Equal(t, ArrayKind, a.Kind())
	assert.Equal(t, x, a.Elem())

	mp := x.AsMapElem(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Elem())

	mp = x.AsMapKey(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Key)

	assert.Equal(t, StringType, x.Elem())

	str := PrefixWriteToString(x, DefaultPrefixer)
	assert.Equal(t, "map[int]string", str)
}

func TestPointerTypeGen(t *testing.T) {
	x := IntType.Pointer()

	assert.Equal(t, PointerKind, x.Kind())
	assert.Equal(t, PkgBuiltin(), x.PackageRef())

	n := x.Named("Foo")
	assert.Equal(t, "Foo", n.Name())
	assert.Equal(t, x, n.T)

	n = x.Unnamed()
	assert.Equal(t, "", n.Name())
	assert.Equal(t, x, n.T)

	p := x.Pointer()
	assert.Equal(t, PointerKind, p.Kind())
	assert.Equal(t, x, p.Elem())

	s := x.Slice()
	assert.Equal(t, SliceKind, s.Kind())
	assert.Equal(t, x, s.Elem())

	a := x.Array(13)
	assert.Equal(t, ArrayKind, a.Kind())
	assert.Equal(t, x, a.Elem())

	mp := x.AsMapElem(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Elem())

	mp = x.AsMapKey(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Key)

	assert.Equal(t, IntType, x.Elem())

	str := PrefixWriteToString(x, DefaultPrefixer)
	assert.Equal(t, "*int", str)
}

func TestSliceTypeTypeGen(t *testing.T) {
	x := IntType.Slice()

	assert.Equal(t, SliceKind, x.Kind())
	assert.Equal(t, PkgBuiltin(), x.PackageRef())

	n := x.Named("Foo")
	assert.Equal(t, "Foo", n.Name())
	assert.Equal(t, x, n.T)

	n = x.Unnamed()
	assert.Equal(t, "", n.Name())
	assert.Equal(t, x, n.T)

	p := x.Pointer()
	assert.Equal(t, PointerKind, p.Kind())
	assert.Equal(t, x, p.Elem())

	s := x.Slice()
	assert.Equal(t, SliceKind, s.Kind())
	assert.Equal(t, x, s.Elem())

	a := x.Array(13)
	assert.Equal(t, ArrayKind, a.Kind())
	assert.Equal(t, x, a.Elem())

	mp := x.AsMapElem(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Elem())

	mp = x.AsMapKey(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Key)

	assert.Equal(t, IntType, x.Elem())

	str := PrefixWriteToString(x, DefaultPrefixer)
	assert.Equal(t, "[]int", str)
}

func TestInterfaceTypeTypeGen(t *testing.T) {
	x := NewInterfaceType(NewFuncSig("Foo", IntType.Unnamed()))

	assert.Equal(t, InterfaceKind, x.Kind())
	assert.Equal(t, PkgBuiltin(), x.PackageRef())

	n := x.Named("Foo")
	assert.Equal(t, "Foo", n.Name())
	assert.Equal(t, x, n.T)

	n = x.Unnamed()
	assert.Equal(t, "", n.Name())
	assert.Equal(t, x, n.T)

	p := x.Pointer()
	assert.Equal(t, PointerKind, p.Kind())
	assert.Equal(t, x, p.Elem())

	s := x.Slice()
	assert.Equal(t, SliceKind, s.Kind())
	assert.Equal(t, x, s.Elem())

	a := x.Array(13)
	assert.Equal(t, ArrayKind, a.Kind())
	assert.Equal(t, x, a.Elem())

	mp := x.AsMapElem(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Elem())

	mp = x.AsMapKey(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Key)

	str := PrefixWriteToString(x, DefaultPrefixer)
	assert.Equal(t, "interface {\n\tFoo(int)\n}", str)
}

func TestInterfaceRefTypeGen(t *testing.T) {
	pkg := MustPackageRef("foo")
	x := pkg.
		NewInterfaceRef("Foo")

	assert.Equal(t, InterfaceKind, x.Kind())
	assert.Equal(t, pkg, x.PackageRef())

	n := x.Named("Foo")
	assert.Equal(t, "Foo", n.Name())
	assert.Equal(t, x, n.T)

	n = x.Unnamed()
	assert.Equal(t, "", n.Name())
	assert.Equal(t, x, n.T)

	p := x.Pointer()
	assert.Equal(t, PointerKind, p.Kind())
	assert.Equal(t, x, p.Elem())

	s := x.Slice()
	assert.Equal(t, SliceKind, s.Kind())
	assert.Equal(t, x, s.Elem())

	a := x.Array(13)
	assert.Equal(t, ArrayKind, a.Kind())
	assert.Equal(t, x, a.Elem())

	mp := x.AsMapElem(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Elem())

	mp = x.AsMapKey(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Key)

	assert.Equal(t, x.Interface, x.Elem())

	str := PrefixWriteToString(x, DefaultPrefixer)
	assert.Equal(t, "foo.Foo", str)
}

func TestStructTypeTypeGen(t *testing.T) {
	x := MustStructType(StringType.Named("Name"))

	assert.Equal(t, StructKind, x.Kind())
	assert.Equal(t, PkgBuiltin(), x.PackageRef())

	n := x.Named("Foo")
	assert.Equal(t, "Foo", n.Name())
	assert.Equal(t, x, n.T)

	n = x.Unnamed()
	assert.Equal(t, "", n.Name())
	assert.Equal(t, x, n.T)

	p := x.Pointer()
	assert.Equal(t, PointerKind, p.Kind())
	assert.Equal(t, x, p.Elem())

	s := x.Slice()
	assert.Equal(t, SliceKind, s.Kind())
	assert.Equal(t, x, s.Elem())

	a := x.Array(13)
	assert.Equal(t, ArrayKind, a.Kind())
	assert.Equal(t, x, a.Elem())

	mp := x.AsMapElem(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Elem())

	mp = x.AsMapKey(IntType)
	assert.Equal(t, MapKind, mp.Kind())
	assert.Equal(t, x, mp.Key)

	str := PrefixWriteToString(x, DefaultPrefixer)
	assert.Equal(t, "struct {\n\tName string\n}", str)
}
