// Generated by gothicgo/bootstrap - Do not modify

package gothicgo

// Named fulfills Type. Returns a NameType with the given name.
func (a *ArrayType) Named(name string) NameType { return NameType{name, a} }

// Unnamed funfills Type. Returns a NameType with an empty Name.
func (a *ArrayType) Unnamed() NameType { return NameType{"", a} }

// Ptr funfills Type.
func (a *ArrayType) Pointer() *PointerType { return PointerTo(a) }

// Slice funfills Type.
func (a *ArrayType) Slice() SliceType { return SliceOf(a) }

// Array funfills Type.
func (a *ArrayType) Array(size int) *ArrayType { return ArrayOf(a, size) }

// AsMapElem funfills Type.
func (a *ArrayType) AsMapElem(key Type) *MapType { return MapOf(key, a) }

// AsMapKey funfills Type. Returns a NameType with an empty Name.
func (a *ArrayType) AsMapKey(elem Type) *MapType { return MapOf(a, elem) }

// Kind fulfills Type. Returns ArrayKind.
func (a *ArrayType) Kind() Kind { return ArrayKind }

// Named fulfills Type. Returns a NameType with the given name.
func (b builtin) Named(name string) NameType { return NameType{name, b} }

// Unnamed funfills Type. Returns a NameType with an empty Name.
func (b builtin) Unnamed() NameType { return NameType{"", b} }

// Ptr funfills Type.
func (b builtin) Pointer() *PointerType { return PointerTo(b) }

// Slice funfills Type.
func (b builtin) Slice() SliceType { return SliceOf(b) }

// Array funfills Type.
func (b builtin) Array(size int) *ArrayType { return ArrayOf(b, size) }

// AsMapElem funfills Type.
func (b builtin) AsMapElem(key Type) *MapType { return MapOf(key, b) }

// AsMapKey funfills Type. Returns a NameType with an empty Name.
func (b builtin) AsMapKey(elem Type) *MapType { return MapOf(b, elem) }

// Named fulfills Type. Returns a NameType with the given name.
func (e *ExternalType) Named(name string) NameType { return NameType{name, e} }

// Unnamed funfills Type. Returns a NameType with an empty Name.
func (e *ExternalType) Unnamed() NameType { return NameType{"", e} }

// Ptr funfills Type.
func (e *ExternalType) Pointer() *PointerType { return PointerTo(e) }

// Slice funfills Type.
func (e *ExternalType) Slice() SliceType { return SliceOf(e) }

// Array funfills Type.
func (e *ExternalType) Array(size int) *ArrayType { return ArrayOf(e, size) }

// AsMapElem funfills Type.
func (e *ExternalType) AsMapElem(key Type) *MapType { return MapOf(key, e) }

// AsMapKey funfills Type. Returns a NameType with an empty Name.
func (e *ExternalType) AsMapKey(elem Type) *MapType { return MapOf(e, elem) }

// Kind fulfills Type. Returns TypeDefKind.
func (e *ExternalType) Kind() Kind { return TypeDefKind }

// Named fulfills Type. Returns a NameType with the given name.
func (f *FuncSig) Named(name string) NameType { return NameType{name, f} }

// Unnamed funfills Type. Returns a NameType with an empty Name.
func (f *FuncSig) Unnamed() NameType { return NameType{"", f} }

// Ptr funfills Type.
func (f *FuncSig) Pointer() *PointerType { return PointerTo(f) }

// Slice funfills Type.
func (f *FuncSig) Slice() SliceType { return SliceOf(f) }

// Array funfills Type.
func (f *FuncSig) Array(size int) *ArrayType { return ArrayOf(f, size) }

// AsMapElem funfills Type.
func (f *FuncSig) AsMapElem(key Type) *MapType { return MapOf(key, f) }

// AsMapKey funfills Type. Returns a NameType with an empty Name.
func (f *FuncSig) AsMapKey(elem Type) *MapType { return MapOf(f, elem) }

// Kind fulfills Type. Returns FuncKind.
func (f *FuncSig) Kind() Kind { return FuncKind }

// Named fulfills Type. Returns a NameType with the given name.
func (m *MapType) Named(name string) NameType { return NameType{name, m} }

// Unnamed funfills Type. Returns a NameType with an empty Name.
func (m *MapType) Unnamed() NameType { return NameType{"", m} }

// Ptr funfills Type.
func (m *MapType) Pointer() *PointerType { return PointerTo(m) }

// Slice funfills Type.
func (m *MapType) Slice() SliceType { return SliceOf(m) }

// Array funfills Type.
func (m *MapType) Array(size int) *ArrayType { return ArrayOf(m, size) }

// AsMapElem funfills Type.
func (m *MapType) AsMapElem(key Type) *MapType { return MapOf(key, m) }

// AsMapKey funfills Type. Returns a NameType with an empty Name.
func (m *MapType) AsMapKey(elem Type) *MapType { return MapOf(m, elem) }

// Kind fulfills Type. Returns MapKind.
func (m *MapType) Kind() Kind { return MapKind }

// Named fulfills Type. Returns a NameType with the given name.
func (p *PointerType) Named(name string) NameType { return NameType{name, p} }

// Unnamed funfills Type. Returns a NameType with an empty Name.
func (p *PointerType) Unnamed() NameType { return NameType{"", p} }

// Ptr funfills Type.
func (p *PointerType) Pointer() *PointerType { return PointerTo(p) }

// Slice funfills Type.
func (p *PointerType) Slice() SliceType { return SliceOf(p) }

// Array funfills Type.
func (p *PointerType) Array(size int) *ArrayType { return ArrayOf(p, size) }

// AsMapElem funfills Type.
func (p *PointerType) AsMapElem(key Type) *MapType { return MapOf(key, p) }

// AsMapKey funfills Type. Returns a NameType with an empty Name.
func (p *PointerType) AsMapKey(elem Type) *MapType { return MapOf(p, elem) }

// Kind fulfills Type. Returns PointerKind.
func (p *PointerType) Kind() Kind { return PointerKind }
